version: "3"

services:
  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file: 
      - ./grafana/.env.gf
    restart: always

  elasticsearch:
    build: ./elkstack/elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elkstack/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

    
  curator:
    build: ./elkstack/curator

  # kibana:
  #   build: ./elkstack/kibana
  #   restart: always
  #    volumes:
  #      - ./elkstack/kibana//kibana.yml:/usr/share/kibana/config/kibana.yml
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
      
  logstash:
    build: ./elkstack/logstash
    restart: always
    volumes:
      - ./elkstack/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./elkstack/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    expose:
      - "5044"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch


volumes:
  esdata:
  grafana-data: