version: "3"

services:
  elasticsearch:
    build: ./elkstack/elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elkstack/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    # depends_on:
    #   - backend

  kibana:
    build: ./elkstack/kibana
    restart: always
    volumes:
      - ./elkstack/kibana//kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      
  logstash:
    build: ./elkstack/logstash
    restart: always
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "9600:9600"
    expose:
      - "5044"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    
  nginx:
    build: ./nginx
    ports:
      - 80:8000
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx

  filebeat:
    build: ./elkstack/filebeat
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx
    links:
      - logstash

volumes:
  esdata: