metricbeat.modules:
#------------------------------- Redis Module -------------------------------
- module: redis
  enabled: true
  metricsets: ["info", "keyspace"]
  period: 5s
  hosts: ["redis:6379"]
#------------------------------- Nginx Module -------------------------------
- module: nginx
  enabled: true
  metricsets: ["stubstatus"]
  period: 5s
  hosts: ["http://nginx"]
  server_status_path: "nginx_status"

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  username: "handshaker"
  password: "zoomin"
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"