FROM docker.elastic.co/elasticsearch/elasticsearch:7.13.2

# Add your elasticsearch plugins setup here
# USER root
# RUN usermod -u 1100 elasticsearch
# USER elasticsearch

# 한국어 형태소 분석기 nori
# RUN bin/elasticsearch-plugin install analysis-nori
